version: '3.8'

services:
  # PostgreSQL 데이터베이스
  db:
    image: postgres:16-alpine
    container_name: sweetspot-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sweetspot
      POSTGRES_PASSWORD: sweetspotpw
      POSTGRES_DB: sweetspot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis 캐싱
  redis:
    image: redis:7-alpine
    container_name: sweetspot-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Minio (S3 호환 스토리지)
  minio:
    image: minio/minio
    container_name: sweetspot-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  # 백엔드 서비스
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sweetspot-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://sweetspot:sweetspotpw@db:5432/sweetspot
      - REDIS_URL=redis://redis:6379
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=sweetspot
      - DEBUG=True
    restart: unless-stopped

  # 프론트엔드 서비스
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sweetspot-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    restart: unless-stopped

  # Prefect 서버
  prefect-server:
    image: prefecthq/prefect:2-python3.10
    container_name: sweetspot-prefect
    ports:
      - "4200:4200"
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_PORT=4200
    volumes:
      - prefect_data:/root/.prefect
    command: ["prefect", "server", "start"]
    restart: unless-stopped

  # Prefect 에이전트
  prefect-agent:
    image: prefecthq/prefect:2-python3.10
    container_name: sweetspot-prefect-agent
    depends_on:
      - prefect-server
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    volumes:
      - ./backend/pipelines:/opt/pipelines
      - prefect_data:/root/.prefect
    command: ["prefect", "agent", "start", "-q", "default"]
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
  prefect_data: 